In [1]:
import pandas as pd

In [2]:
data1=pd.read_csv('data.csv')

In [3]:
data1

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [4]:
x=data1["YearsExperience"]
x

0      1.1
1      1.3
2      1.5
3      2.0
4      2.2
5      2.9
6      3.0
7      3.2
8      3.2
9      3.7
10     3.9
11     4.0
12     4.0
13     4.1
14     4.5
15     4.9
16     5.1
17     5.3
18     5.9
19     6.0
20     6.8
21     7.1
22     7.9
23     8.2
24     8.7
25     9.0
26     9.5
27     9.6
28    10.3
29    10.5
Name: YearsExperience, dtype: float64

In [5]:
y=data1["Salary"]
y

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=10)

In [7]:
x_train_reshape=x_train.values.reshape(-1,1)
y_train_reshape=y_train.values.reshape(-1,1)
x_test_reshape=x_test.values.reshape(-1,1)
y_test_reshape=x_test.values.reshape(-1,1)

In [8]:
from sklearn.linear_model import LinearRegression
lin_model=LinearRegression().fit(x_train_reshape,y_train_reshape)

In [9]:
y_pred=lin_model.predict(x_test_reshape)

In [10]:
y_pred

array([[ 90329.26994588],
       [ 56076.98533315],
       [ 53222.62828209],
       [ 39902.29537714],
       [ 44659.55712891],
       [ 93183.62699694],
       [ 64640.05648633],
       [116969.93575577],
       [ 63688.60413598],
       [ 37999.39067643]])

In [11]:
x_test_reshape

array([[6.8],
       [3.2],
       [2.9],
       [1.5],
       [2. ],
       [7.1],
       [4.1],
       [9.6],
       [4. ],
       [1.3]])

In [12]:
y_train_pred=lin_model.predict(x_train_reshape)

In [13]:
y_train_pred

array([[ 82717.65114305],
       [ 68445.86588775],
       [ 81766.19879269],
       [ 54174.08063244],
       [ 63688.60413598],
       [103649.60285082],
       [108406.86460259],
       [123630.10220825],
       [100795.24579976],
       [ 62737.15178562],
       [116018.48340542],
       [125533.00690896],
       [ 56076.98533315],
       [111261.22165365],
       [ 74154.57998987],
       [ 76057.48469057],
       [ 36096.48597573],
       [ 72251.67528916],
       [ 46562.46182961],
       [ 60834.24708492]])

In [14]:
from sklearn.metrics import r2_score

In [15]:
print(r2_score(y_train_reshape,y_train_pred))

0.9504480256569947
